name: "Deploy Subgraph"

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network name in lowercase"
        required: true

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "18"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Lint the code"
        run: "yarn run lint"

      - name: "Generate the subgraph manifest"
        run: "yarn run prepare:mainnet"

      - name: "Generate the AssemblyScript types"
        run: "yarn run codegen"

      - name: "Deploy to ${{ inputs.network }}"
        run: yarn run deploy:${{ inputs.network }} --access-token ${{ secrets.THE_GRAPH_TOKEN }}
