name: "Deploy Subgraphs"

on: workflow_dispatch

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Lint the code"
        run: "yarn lint"

      - name: "Generate the subgraph manifest"
        run: "yarn prepare:mainnet"

      - name: "Generate the AssemblyScript types"
        run: "yarn codegen"

      - name: "Deploy to Goerli"
        run: yarn deploy:goerli --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Kovan"
        run: yarn deploy:kovan --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Rinkeby"
        run: yarn deploy:rinkeby --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Ropsten"
        run: yarn deploy:ropsten --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Mainnet"
        run: yarn deploy:mainnet --access-token ${{ secrets.THE_GRAPH_TOKEN }}
