name: "Integration"

on:
  push:
    branches:
      - "main"

jobs:
  integration:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Lint the code"
        run: "yarn lint"

      - name: "Generate the subgraph manifest"
        run: "yarn prepare:mainnet"

      - name: "Generate the AssemblyScript types"
        run: "yarn codegen"

      - name: "Build the subgraph"
        run: "yarn build"
